apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    environment: blue  # Initially points to blue environment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 